---
- name: Create Sonarr directory
  file:
    path: "{{ data_root }}/sonarr"
    state: directory
    mode: '0755'

- name: Deploy Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: "lscr.io/linuxserver/sonarr:{{ sonarr_version }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "{{ ports.sonarr }}:8989"
    volumes:
      - "{{ data_root }}/sonarr:/config"
      - "{{ data_root }}/media/tv:/tv"
      - "{{ data_root }}/downloads:/downloads"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ timezone }}"
